---
title: "R Notebook"
output: html_notebook
---


```{r}
library("TDA")
#library("ncdf4")
#library("psych")
#library("reticulate")
filename1<-"pca.csv"
filename2<-"region55.csv"
filename3<-"region65.csv"
foldername<-"ECWMF Datasets"
ncfpath1<-paste(getwd(),filename1,sep = "/")
ncfpath2<-paste(getwd(),filename2,sep = "/")
ncfpath3<-paste(getwd(),filename3,sep = "/")
#data<-nc_open(ncfpath)
#g<-9.80655

#lonLength<-length(ncvar_get(data,"lon"))
#latLength<-length(ncvar_get(data,"lat"))

#geopotentialIsobaric<-ncvar_get(data,"Geopotential_isobaric")
#geopotentialIsobaric500<-geopotentialIsobaric[,,8,]/g

#geopotentialIsobaric500Reshaped<-matrix(geopotentialIsobaric500,nrow = 51,ncol = lonLength*latLength)


#data_pca<-principal(geopotentialIsobaric500Reshaped,nfactors = 9)
# oPCA<-prcomp(geopotentialIsobaric500Reshaped,center = TRUE,rank. = 9)
# data_pca<-oPCA$x
#pca<-import("sklearn")
#source_python("pcaData.py")

data_pca<-read.csv(file = ncfpath1,header = FALSE, sep = ",")
data_55<-read.csv(file = ncfpath2,header = FALSE, sep = ",")
data_65<-read.csv(file = ncfpath3,header = FALSE, sep = ",")


#plot(Tree,type = "alpha",main = "alpha Tree (knn)")
```
```{r}
X<-data_pca
k<-4
#Tree<-clusterTree(X,k,density = "knn")
TreeKDE<-clusterTree(X,k,h=664 ,density = "kde")
plot(TreeKDE,type = "alpha",main="alpha Tree (kde)")
```
```{r}
TreeKDE$DataPoints
```

```{r}
X<-data_55
k<-2
#Tree<-clusterTree(X,k,density = "knn")
TreeKDE<-clusterTree(X,k,h=332 ,density = "kde")
plot(TreeKDE,type = "alpha",main="alpha Tree (kde)")
```
```{r}
TreeKDE$DataPoints
```

```{r}
X<-data_65
k<-2
#Tree<-clusterTree(X,k,density = "knn")
TreeKDE<-clusterTree(X,k,h=664 ,density = "kde")
plot(TreeKDE,type = "alpha",main="alpha Tree (kde)")
```

```{r}
TreeKDE$DataPoints
```

